config/routes.rb
Rails.application.routes.draw do
  root "rooms#search"
  
  devise_for :users
  namespace :users do
    get 'profile', to: 'profile#show'
    get 'profile/edit'
    patch 'profile/update'
    
    get 'account', to: 'account#show'
  end
  
  get "rooms/own", to: "rooms#own"
  resources :rooms
  
  scope(path_names: { new: "confirm" }) do
    resources :reservations, except: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  before_create :default_image
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :reservations, dependent: :destroy
  has_many :rooms, through: :reservations
  has_many :rooms
  before_destroy :destroy_rooms
  has_one_attached :avater
  
  private
  def default_image
    if !self.avater.attached?
      self.avater.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'default_avater.png')),
      filename: 'default_avater.png',
      content_type: 'image/png')
    end
  end

  def destroy_rooms
    rooms.destroy_all
  end
  
end

app/controllers/users/account_controller.rb
class Users::AccountController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = current_user
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/profile_controller.rb
class Users::ProfileController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = current_user
  end
  
  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(profile_params)
      redirect_to users_profile_path, notice: 'プロフィール情報が更新されました'
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:user).permit(:name, :profile, :avater)
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/users/account_helper.rb
module Users::AccountHelper
end

app/helpers/users/profile_helper.rb
module Users::ProfileHelper
end

app/views/users/profile/edit.html.erb
<div class="my-20 mx-10">
  <div class="w-1/2 mx-auto border-2 rounded-md p-5">
    <p class="text-2xl">プロフィール編集</p>

    <div class="mt-10 mb-5">
      <%= form_with model: @user, url: users_profile_update_path do |f| %>
        <div class="space-y-6 mb-5">
          <div class="flex justify-between">
            <%= f.label :name %>
            <div class="flex flex-col">
              <%= f.text_field :name, class: "input w-80" %>
              <% if @user.errors.include?(:name) %>
                <p class="text-sm text-red-500"><%= @user.errors.full_messages_for(:name).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :profile %>
            <%= f.text_area :profile, class: "input" %>
          </div>
          <div class="flex justify-between">
            <%= f.label :avater %>
            <%= f.file_field :avater, class: "file-input" %>
          </div>
        </div>
        <%= f.submit "作成", class: "btn btn-primary w-full" %>
      <% end %>
    </div>

    <%= link_to "キャンセル", :back, class: "btn w-full text-xs" %>
  </div>
</div>

app/views/users/profile/show.html.erb
<div class="mx-10 my-20">
  <div class="flex space-x-12">
    <div class="w-1/5">
      <%= link_to "アカウント", users_account_path, class: "border p-5 block" %>
      <%= link_to "プロフィール", users_profile_path, class: "text-orange-500 border p-5 block" %>
    </div>
    <div class="w-full">
      <div class="border-b flex justify-between p-2 items-center">
        <h1 class="text-2xl">プロフィール</h1>
        <%= link_to "編集", users_profile_edit_path, class: "text-xl text-blue-500 link mr-5" %>
      </div>

      <div class="px-2 py-5 space-y-5">
        <div class="flex">
          <p class="w-1/4 font-bold content-center">アイコン画像</p>
          <%= image_tag @user.avater, class: "size-20 object-cover rounded-full" %>
        </div>
        <div class="flex">
          <p class="w-1/4 font-semibold">名前</p>
          <p class="w-3/4"><%= @user.name %></p>
        </div>
        <div class="flex text-wrap">
          <p class="w-1/4 font-semibold">自己紹介</p>
          <p class="w-3/4"><%= @user.profile %></p>
        </div>
      </div>
    </div>
  </div>
</div>