config/routes.rb
Rails.application.routes.draw do
  root "rooms#search"
  
  devise_for :users
  namespace :users do
    get 'profile', to: 'profile#show'
    get 'profile/edit'
    patch 'profile/update'
    
    get 'account', to: 'account#show'
  end
  
  get "rooms/own", to: "rooms#own"
  resources :rooms
  
  scope(path_names: { new: "confirm" }) do
    resources :reservations, except: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :check_in_date, presence: true
  validate :check_in_greater_than_today
  validates :check_out_date, presence: true
  validate :greater_than_check_in
  validates :member_count, presence: true
  validate :greater_than_zero_member_count

  def check_in_greater_than_today
    if check_in_date.present? && check_in_date < Date.today
      errors.add(:check_in_date, "は本日以降の日付で選択して下さい")
    end
  end

  def greater_than_check_in
    if check_in_date.present? && check_out_date.present? && check_in_date >= check_out_date
      errors.add(:check_out_date, "はチェックイン日より後ろに設定してください")
    end
  end

  def greater_than_zero_member_count
    if member_count.present? && member_count < 1
      errors.add(:member_count, "は0より大きい値にしてください")
    end
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def new
    @reservation = Reservation.new(reservation_params)
    @room = Room.find(@reservation.room_id)

    unless @reservation.valid?
      render "rooms/show"
      return
    end
  end

  def index
    @reservations = Reservation.where(user_id: current_user.id)
  end

  def create
    @reservation = Reservation.new(reservation_params)
    if @reservation.save
      flash[:info] = "予約しました"
      redirect_to reservations_path
    else
      flash.now[:error] = "予約できませんでした"
      render :new
    end
  end

  def edit
    @reservation = Reservation.find(params[:id])
  end

  def update
    @reservation = Reservation.find(params[:id])
    if @reservation.update(reservation_params)
      flash[:info] = "再予約しました"
      redirect_to reservations_path
    else
      flash.now[:error] = "再予約できませんでした"
      render :edit
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy!
    flash[:info] = "予約を取り消しました"
    redirect_to reservations_path
  end

  private
  def reservation_params
    params.require(:reservation).permit(:check_in_date, :check_out_date, :member_count, :room_id).merge(user_id: current_user.id)
  end

end

app/helpers/reservations_helper.rb
module ReservationsHelper
  def total_fee(reservation)
  (reservation.check_out_date.to_date - reservation.check_in_date.to_date).to_i * reservation.room.fee * reservation.member_count
  end
end

app/views/reservations/_reservation.html.erb
  <tr class="border-b">
    <td class="py-4"><%= image_tag reservation.room.image, class: "w-24" %></td>
    <td class="py-4 text-blue-500 hover:text-blue-800"><%= link_to reservation.room.name, room_path(reservation.room) %></td>
    <td class="py-4"><%= reservation.room.introduction %></td>
    <td class="py-4">¥<%= total_fee(reservation).to_s(:delimited) %></td>
    <td class="py-4"><%= l(reservation.check_in_date, format: :default) %></td>
    <td class="py-4"><%= l(reservation.check_out_date, format: :default) %></td>
    <td class="py-4"><%= l(reservation.created_at, format: :long) %></td>
    <td>
      <details class="dropdown">
        <summary class="btn btn-ghost m-1">
          <div>
            <img id="dropdown" width="18" height="18" src="https://img.icons8.com/material-rounded/24/menu-2.png" alt="menu-2" class="opacity-80"/>
          </div>
        </summary>
        <ul class="menu dropdown-content bg-base-100 rounded-box z-1 w-52 p-2 -left-28 shadow-sm">
          <li>            
            <%= link_to "再予約", edit_reservation_path(reservation.id) %>
          </li>
          <li>
            <label for="delete_modal" class="text-red-500">予約取り消し</label>
          </li>
        </ul>
      </details>
    </td>
    <td></td>
  </tr>

<input type="checkbox" id="delete_modal" class="modal-toggle" />
<div class="modal" role="dialog">
  <div class="modal-box">
    <h3 class="text-lg font-bold">以下の施設を削除しますか？</h3>
    <div class="flex py-3 space-x-3">
      <div>
        <%= image_tag reservation.room.image, class: "w-20 h-16" %>
      </div>
      <div>
        <p><%= reservation.room.name %></p>
        <p><%= "#{l(reservation.check_in_date, format: :default)} 〜 #{l(reservation.check_out_date, format: :default)}" %></p>
        <p><%= reservation.member_count %> 人</p>
        <p>¥ <%= total_fee(reservation).to_s(:delimited) %></p>
      </div>
    </div>
    <p>よろしければ削除ボタンを押してください</p>
    <div class="flex justify-between">
      <div class="modal-action">
        <label for="delete_modal" class="btn">キャンセル</label>
      </div>
      <%= link_to "削除", reservation_path(reservation.id), method: :delete, class: "btn btn-error mt-6" %>
    </div>
  </div>
</div>

app/views/reservations/edit.html.erb
<div class="my-20 mx-10">
  <div class="w-2/3 mx-auto">
    <div class="mb-16 space-y-10">
      <%= image_tag @reservation.room.image %>
      <div class="flex justify-between w-4/5">
        <div class="opacity-80">
          <p class="text-xl"><%= @reservation.room.name %></p>
          <p><%= @reservation.room.address %></p>
        </div>
        <div>
          <p class="text-xl text-blue-500">¥<%= @reservation.room.fee.to_s(:delimited) %>~</p>
        </div>
      </div>
    </div>
    <div class="border-2 rounded-md p-5">
      <h1 class="text-2xl mb-8">再予約</h1>

      <%= form_with model: @reservation do |f| %>
        <div class="space-y-5">
          <div class="flex justify-between">
            <%= f.label :check_in_date %>
            <div class="w-1/3">
              <%= f.date_field :check_in_date, class: "input" %>
              <% if @reservation.errors.include?(:check_in_date) %>
                <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:check_in_date).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :check_out_date %>
            <div class="w-1/3">
              <%= f.date_field :check_out_date, class: "input" %>
              <% if @reservation.errors.include?(:check_out_date) %>
                <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:check_out_date).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :member_count %>
            <div class="w-1/3">
              <%= f.text_field :member_count, class: "input" %>
              <% if @reservation.errors.include?(:member_count) %>
                <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:member_count).first %></p>
              <% end %>

            </div>
          </div>
          <div class="flex flex-col space-y-5"> 
            <%= f.submit "再予約する", class: "btn btn-primary" %>
            <%= link_to "キャンセル", 'javascript:history.back()', class: "btn" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reservations/index.html.erb
<div class="w-screen mx-10 my-20">
  <h1 class="text-3xl mb-10">予約済み一覧</h1>

  <table class="w-full">
    <thead>
      <tr class="border-b border-b-black text-left">
        <th class="py-2">画像</th>
        <th class="py-2">施設名</th>
        <th class="py-2">紹介文</th>
        <th class="py-2">合計料金</th>
        <th class="py-2">チェックイン</th>
        <th class="py-2">チェックアウト</th>
        <th class="py-2">予約確定日時</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render @reservations %>
    </tbody>
  </table>
</div>

app/views/reservations/new.html.erb
<div class="my-20 mx-10">
  <div class="w-1/2 mx-auto border-2 rounded-md p-5 flex flex-col space-y-5">
    <h1 class="text-2xl">予約確認</h1>
    <div class="flex justify-between">
      <p>チェックイン</p>
      <p><%= @reservation.check_in_date %></p>
    </div>
    <div class="flex justify-between">
      <p>チェックアウト</p>
      <p><%= @reservation.check_out_date %></p>
    </div>
    <div class="flex justify-between">
      <p>日数</p>
      <p><%= (@reservation.check_out_date - @reservation.check_in_date).to_i %>日</p>
    </div>
    <div class="flex justify-between">
      <p>人数</p>
      <p><%= @reservation.member_count %>人</p>
    </div>
    <div class="flex justify-between font-semibold">
      <p>お支払い金額</p>
      <p>¥<%= ((@reservation.check_out_date.to_date - @reservation.check_in_date.to_date).to_i * @reservation.room.fee * @reservation.member_count).to_s(:delimited) %></p>
    </div>
    
    <%= form_with model: @reservation do |f| %>
      <%= f.hidden_field :check_in_date %>
      <%= f.hidden_field :check_out_date %>
      <%= f.hidden_field :member_count %>
      <%= f.hidden_field :room_id %>
      <%= f.submit "予約する", class: "btn btn-primary w-1/3" %>
    <% end %>

    <%= link_to "キャンセル", :back, class: "btn w-1/3" %>
  </div>
</div>