config/routes.rb
Rails.application.routes.draw do
  root "rooms#search"
  
  devise_for :users
  namespace :users do
    get 'profile', to: 'profile#show'
    get 'profile/edit'
    patch 'profile/update'
    
    get 'account', to: 'account#show'
  end
  
  get "rooms/own", to: "rooms#own"
  resources :rooms
  
  scope(path_names: { new: "confirm" }) do
    resources :reservations, except: [:show]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  before_create :default_image

  belongs_to :user
  has_many :reservations, dependent: :destroy
  has_many :users, through: :reservations
  has_one_attached :image

  validates :name, presence: true
  validates :address, presence: true
  validates :fee, presence: true

  validate :check_fee_minimum

  scope :area_query, -> (q){
    return all if q.blank?
    where("address LIKE ?", "%#{sanitize_sql_like(q)}%")
  }
  scope :room_query, -> (q){
    return all if q.blank?

    where("name LIKE ?", "%#{sanitize_sql_like(q)}%")
      .or(where("introduction LIKE ?", "%#{sanitize_sql_like(q)}%"))
  }

  def default_image
    if !self.image.attached?
      self.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'room_image.png')),
      filename: 'room_image.png',
      content_type: 'image/png')
    end
  end

  def check_fee_minimum
    errors.add(:fee, "は1円以上に設定してください") if fee.nil? || fee < 1
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:own, :new, :edit, :update, :destroy, :create]

  def search
  end

  def index
    @rooms = Room.area_query(params[:area_q]).room_query(params[:room_q])
  end

  def own
    @rooms = current_user.rooms
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:info] = "作成しました！"
      redirect_to room_path(@room.id)
    else
      flash.now[:error] = "失敗しました"
      render :new
    end
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end
  
  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])
    if @room.update(room_params)
      flash[:info] = "更新しました"
      redirect_to room_path(@room.id)
    else
      flash.now[:error] = "失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy!
    flash[:info] = "施設情報を削除しました"
    redirect_to rooms_path, status: :see_other
  end

  private
  def room_params
    params.require(:room).permit(:name, :image, :introduction, :address, :fee).merge(user_id: current_user.id)
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_room.html.erb
<div class="card bg-stone-300 w-96 shadow-sm">
  <figure class="h-52">
    <%= image_tag room.image %>
  </figure> 
  <div class="card-body">
    <p class="text-xl opacity-50"><%= room.name %></p>
    <p class="opacity-50"><%= room.address %></p>
    <p class="my-3 line-clamp-3 break-words"><%= room.introduction %></p>
    <p class="text-2xl text-blue-500 mb-3">¥<%= room.fee.to_s(:delimited) %>~</p>
    <% if controller.action_name == "own" %>
      <%= link_to "編集", edit_room_path(room.id), class: "btn btn-primary" %>
      <label for="delete_modal" class="btn btn-error">削除</label>
    <% else %>
      <%= link_to "詳細はこちら", room_path(room.id), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<input type="checkbox" id="delete_modal" class="modal-toggle" />
<div class="modal" role="dialog">
  <div class="modal-box">
    <h3 class="text-lg font-bold">以下の施設を削除しますか？</h3>
    <div class="flex py-3 space-x-3">
      <div>
        <%= image_tag room.image, class: "w-20 h-16" %>
      </div>
      <div>
        <p><%= room.name %></p>
        <p>¥<%= room.fee.to_s(:delimited) %> ~ /日</p>
      </div>
    </div>
    <p>よろしければ削除ボタンを押してください</p>
    <div class="flex justify-between">
      <div class="modal-action">
        <label for="delete_modal" class="btn">キャンセル</label>
      </div>
      <%= link_to "削除", room_path(room.id), method: :delete, class: "btn btn-error mt-6" %>
    </div>
  </div>
</div>

app/views/rooms/_search_form.html.erb
<div class="bg-stone-300 h-24 flex items-center justify-center">
  <%= form_with url: rooms_path, method: :get do |f| %>
    <div class="flex justify-center space-x-6 items-center">
        <%= f.text_field :area_q, placeholder: "エリア名を入力", class: "input" %>
        <%= f.text_field :room_cq, placeholder: "フリーワード検索", class: "input" %>
        <%= f.submit "検索", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/rooms/edit.html.erb
<div class="my-20 mx-10">
  <div class="w-1/2 mx-auto border-2 rounded-md p-5">
    <p class="text-2xl">施設情報の編集</p>

    <div class="mt-10 mb-5">
      <%= form_with model: @room do |f| %>
        <div class="space-y-6 mb-5">
          <div class="flex justify-between">
            <%= f.label :name, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :name, class: "input w-80" %>
              <% if @room.errors.include?(:name) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:name).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :address, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :address, class: "input w-80" %>
              <% if @room.errors.include?(:address) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:address).first %></p>
              <% end %>
            </div>
          </div> 
          <div class="flex justify-between"> 
            <%= f.label :fee, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :fee, class: "input w-80" %>
              <% if @room.errors.include?(:fee) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:fee).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :introduction, class: "" %>
            <div class="flex flex-col">
              <%= f.text_area :introduction, class: "input w-80" %>
              <% if @room.errors.include?(:introduction) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:introduction).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :image, class: "" %>
            <div class="flex flex-col">
              <%= f.file_field :image, class: "file-input" %>
              <% if @room.errors.include?(:image) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:image).first %></p>
              <% end %>
            </div>
          </div>
        </div>
        <%= f.submit "更新", class: "btn btn-primary w-1/6" %>
      <% end %>
    </div>

    <%= link_to "キャンセル", :back, class: "btn w-1/6 text-xs" %>
  </div>
</div>

app/views/rooms/index.html.erb
<div class="w-screen">
  <%= render "search_form" %>
  <div class="my-10 mx-12">
    <p class="text-2xl">
      <span class="font-semibold"><%= @rooms.count %></span> 件見つかりました
    </p>
  </div>
  <div class="grid grid-cols-2 lg:grid-cols-3 gap-8 px-10">
    <%= render @rooms %>
  </div>
</div>

app/views/rooms/new.html.erb
<div class="my-20 mx-10">
  <div class="w-1/2 mx-auto border-2 rounded-md p-5">
    <p class="text-2xl">施設作成</p>

    <div class="mt-10 mb-5">
      <%= form_with model: @room do |f| %>
        <div class="space-y-6 mb-5">
          <div class="flex justify-between">
            <%= f.label :name, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :name, class: "input w-80" %>
              <% if @room.errors.include?(:name) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:name).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :address, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :address, class: "input w-80" %>
              <% if @room.errors.include?(:address) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:address).first %></p>
              <% end %>
            </div>
          </div> 
          <div class="flex justify-between"> 
            <%= f.label :fee, class: "" %>
            <div class="flex flex-col">
              <%= f.text_field :fee, class: "input w-80" %>
              <% if @room.errors.include?(:fee) %>
                <p class="text-sm text-red-500"><%= @room.errors.full_messages_for(:fee).first %></p>
              <% end %>
            </div>
          </div>
          <div class="flex justify-between">
            <%= f.label :introduction, class: "" %>
            <%= f.text_area :introduction, class: "input" %>
          </div>
          <div class="flex justify-between">
            <%= f.label :image, class: "" %>
            <%= f.file_field :image, class: "file-input" %>
          </div>
        </div>
        <%= f.submit "作成", class: "btn btn-primary w-1/6" %>
      <% end %>
    </div>

    <%= link_to "キャンセル", :back, class: "btn w-1/6 text-xs" %>
  </div>
</div>

app/views/rooms/own.html.erb
<div class="w-screen mx-10 my-20">
  <h1 class="text-3xl">作成済み施設一覧</h1>

  <div class="grid grid-cols-2 lg:grid-cols-3 gap-8 mt-10">
    <%= render @rooms %>
  </div>
</div>

app/views/rooms/search.html.erb
<div class="w-full py-16 shadow-md">
  <div class="w-80 mx-auto">
    <%= form_with url: rooms_path, method: :get do |f| %>
        <%= f.text_field :area_q, placeholder: "エリア名を入力", class: "input mb-5" %>
        <%= f.submit "検索", class: "btn w-full" %>
    <% end %>
  </div>
</div>
<div class="mx-28 my-24">
  <h1 class="text-3xl mb-20">おすすめエリア</h1>
  <div class="grid grid-cols-3 gap-6">
    <div class="h-96 w-64 relative">
      <%= link_to rooms_path(area_q: "東京") do %>
        <%= image_tag 'Tokyo.jpg', class: "h-full object-cover rounded-3xl" %>
      <% end %>
      <div class="absolute bottom-6 left-5">
        <p class="text-white text-2xl font-semibold">東京</p>
      </div>
    </div>
    <div class="h-96 w-64 relative">
      <%= link_to rooms_path(area_q: "大阪") do %>
        <%= image_tag 'Osaka.jpg', class: "h-full object-cover rounded-3xl" %>
      <% end %>
      <div class="absolute bottom-6 left-5">
        <p class="text-white text-2xl font-semibold">大阪</p>
      </div>
    </div>
    <div class="h-96 w-64 relative">
      <%= link_to rooms_path(area_q: "京都") do %>
        <%= image_tag 'Kyoto.jpg', class: "h-full object-cover rounded-3xl" %>
      <% end %>
      <div class="absolute bottom-6 left-5">
        <p class="text-white text-2xl font-semibold">京都</p>
      </div>
    </div>
    <div class="h-96 w-64 relative">
      <%= link_to rooms_path(area_q: "札幌") do %>
        <%= image_tag 'Sapporo.jpg', class: "h-full object-cover rounded-3xl" %>
      <% end %>
      <div class="absolute bottom-6 left-5">
        <p class="text-white text-2xl font-semibold">札幌</p>
      </div>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="w-screen">
  <%= render "rooms/search_form" %>
  <div class="mx-10 my-8  flex justify-between text-blue-500 font-medium text-xl">
    <%= link_to "戻る", 'javascript:history.back()', class: "hover:text-blue-600" %>
    <%= link_to "編集", edit_room_path(@room.id), class: "hover:text-blue-600" %>
  </div>

  <div class="flex justify-between mx-10">
    <div class="w-2/5">
      <%= image_tag @room.image %>
    </div>

    <div class="border-4 rounded-lg py-10 px-5 w-[55%]">
      <div class="flex justify-between">
        <div class="mb-10 space-y-3">
          <p class="text-3xl opacity-60"><%= @room.name %></p>
          <p class="opacity-60"><%= @room.address %></p>
        </div>
        <div>
          <p class="text-2xl text-blue-500">¥<%= @room.fee.to_s(:delimited) %>~</p>
        </div>
      </div>
      <div>
        <p class="opacity-90"><%= @room.introduction %></p>
      </div>

      <div class="mt-10 border-2 py-8 px-10 bg-blue-50">
        <%= form_with model: @reservation, url: new_reservation_path, method: :get do |f| %>
          <%= f.hidden_field :room_id, value: @room.id %>
          <div class="flex justify-between mb-10">
            <div class="flex flex-col w-48 text-wrap">
              <%= f.label :check_in_date, class: "" %>
                <%= f.date_field :check_in_date, class: "input" %>
                <% if @reservation.errors.include?(:check_in_date) %>
                  <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:check_in_date).first %></p>
                <% end %>
            </div>
            <div class="flex flex-col w-48 text-wrap">
              <%= f.label :check_out_date, class: "" %>
                <%= f.date_field :check_out_date, class: "input w-full" %>
                <% if @reservation.errors.include?(:check_out_date) %>
                  <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:check_out_date).first %></p>
                <% end %>
            </div>
            <div class="flex flex-col w-48 text-wrap">
              <%= f.label :member_count, class: "" %>
                <%= f.text_field :member_count, class: "input w-full" %>
                <% if @reservation.errors.include?(:member_count) %>
                  <p class="text-sm text-red-500"><%= @reservation.errors.full_messages_for(:member_count).first %></p>
                <% end %>
            </div>
          </div>
          <%= f.submit "予約する", class: "btn btn-info w-full mx-auto h-12" %>
        <% end %>
      </div>
    </div>
  </div>
</div>